package com.model.pojo;
// Generated Sep 20, 2024 1:42:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,catalog="flow_manage"
)
public class Project  implements java.io.Serializable {


     private int id;
     private Status status;
     private String title;
     private String overview;
     private Date deadline;
     private Set users = new HashSet(0);
     private Set tasks = new HashSet(0);

    public Project() {
    }

	
    public Project(int id, Status status, String title, String overview, Date deadline) {
        this.id = id;
        this.status = status;
        this.title = title;
        this.overview = overview;
        this.deadline = deadline;
    }
    public Project(int id, Status status, String title, String overview, Date deadline, Set users, Set tasks) {
       this.id = id;
       this.status = status;
       this.title = title;
       this.overview = overview;
       this.deadline = deadline;
       this.users = users;
       this.tasks = tasks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status_id", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="overview", nullable=false, length=65535)
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deadline", nullable=false, length=10)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="project_worker", catalog="flow_manage", joinColumns = { 
        @JoinColumn(name="project_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


