package com.model.pojo;
// Generated Sep 20, 2024 1:42:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status"
    ,catalog="flow_manage"
)
public class Status  implements java.io.Serializable {


     private int id;
     private String status;
     private Set projects = new HashSet(0);
     private Set tasks = new HashSet(0);

    public Status() {
    }

	
    public Status(int id, String status) {
        this.id = id;
        this.status = status;
    }
    public Status(int id, String status, Set projects, Set tasks) {
       this.id = id;
       this.status = status;
       this.projects = projects;
       this.tasks = tasks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


